### ISSUE TITLE
Mails might become truncated because of inserted newlines.

### ISSUE THREAD

**Issue by raichoo** [snoyberg/mime-mail#41]
Hi,

I had some issues with mail being truncated for what looked like no reason at all. Digging deeper I found the following problem.

`Network.Mail.Mime` inserts newlines whenever lines are getting too long. This
however can results in a `.` ending up on a single line signaling `sendmail` the end of
the mail and discards whatever text might follow.

    {-# LANGUAGE OverloadedStrings #-}
    module Bug where

    import Prelude hiding (putStrLn)

    import Network.Mail.Mime
    import Data.ByteString.Lazy.Char8 (putStrLn)

    mail =
      simpleMail'
        (Address Nothing "foo@bar.com")
        (Address Nothing "foo@bar.com")
        "Subject"
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxöxxxxxxxxxxxxxxxxxxöxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxöxxxxxxxxxxxxxxxxxxxxxxxxxxxxöxxxxx.\n"

    test :: IO ()
    test = renderMail' mail >>= putStrLn

This code results in the following mail:

    From: <foo@bar.com>
    To: <foo@bar.com>
    Subject: Subject
    MIME-Version: 1.0
    Content-Type: text/plain; charset=utf-8
    Content-Transfer-Encoding: quoted-printable

    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=C3=B6xxxxxxxxxxxxxxxxxx=C3=B6xxxxxxxx=
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=C3=B6xxxxxxxxxxxxxxxxxxxxxxxxxxxx=C3=B6xxxxx=
    .

In my case there was still text after the newline which then got cut off. As a current workaround I'm inserting newlines myself to suppress this effect but this is quite unfortunate since adding special characters like those above might lead to longer lines than expected, triggering this behavior in unexpected situations.

Kind regards,
raichoo

**Comment by snoyberg** [comment]
Thanks for the report. Do you know how other MIME libraries handle this issue?

**Comment by raichoo** [comment]
Sadly I don't, otherwise I would have sent a patch right away :)

**Comment by snoyberg** [comment]
Perhaps it's as simple as doing a check if any lines contain only "." and,
if so, escaping the period?

**Comment by snoyberg** [comment]
I pushed a commit that always escapes periods, but I'm not convinced it's the right thing to do. It's perfectly valid to have a line with just a period in it in a MIME message, just not as input to sendmail. Instead, it may be better to escape those lines in `sendmailCustom`.

Anyway, can you try out the patch?

**Comment by raichoo** [comment]
Thanks,
seems to work properly. When are you planning to push this, so that I can update our cabal files to depend on that specific version?

Thanks for reacting so fast :)

Kind regards,
raichoo

**Comment by snoyberg** [comment]
It's now on Hackage.

**Comment by raichoo** [comment]
Thanks a bunch :)
