### ISSUE TITLE
Proper way to set Content-ID of an attachment

### ISSUE THREAD

**Issue by sras** [snoyberg/mime-mail#47]
What is the proper way to set the Content-ID for an attachment using this library? I want to refer to the attachment from the html content of the mail.

I can do this by modifying the headers in the alternatives field of the Mail. But I am looking for a high level api for doing things like this.

**Comment by snoyberg** [comment]
No such high level API exists right now, but if you'd like to send a PR to
add such a function that would be great.

**Comment by sras** [comment]
I have sent a PR. https://github.com/snoyberg/mime-mail/pull/48

**Comment by kindaro** [comment]
I am closing this since it appears to be solved in #48.
