### ISSUE TITLE
Add another function named `sendMailSES'`

### ISSUE THREAD

**Issue by psibi** [snoyberg/mime-mail#55]
It's type signature would be like this:

```
sendMailSES' :: MonadIO m => SES -> ByteString -> m () 
```

It would be using global manager from the `http-client-tls` package.

Motivation: I'm internally using this function in several of my Yesod apps.

I can send a PR if there is no objections.

**Comment by snoyberg** [comment]
Seems reasonable. Maybe `sendMailSESGlobal` would be a good name, but I'm really not picky here.

**Comment by danchoi** [comment]
I think it's probably better if I ask to be removed from the maintainer list as I've been much busier with other things than expected to be able to help maintain this library. Maybe @psibi can volunteer to take my place?

**Comment by psibi** [comment]
I don't mind maintaining it!

**Comment by kindaro** [comment]
It seems that this issue is resolved by #56 — I am closing it for now, but @psibi please let me know if there is something else to do here and I shall reopen.
