### ISSUE TITLE
Use AWS signature version 4 (required starting October 2020)

### ISSUE THREAD

**Issue by limick** [snoyberg/mime-mail#60]
The `mime-mail-ses` package currently uses Signature Version 3, as can be seen by the string "AWS3-HTTPS" in the `X-Amzn-Authorization` header [1]. Starting 1 October 2020, AWS SES will require clients to use Signature Version 4 [2].

Unless fixed until then, the `sendMailSES` function will no longer work.

[1] https://www.stackage.org/haddock/lts-16.5/mime-mail-ses-0.4.1/src/Network.Mail.Mime.SES.html#sendMailSES
[2] https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html

**Comment by snoyberg** [comment]
I won't be able to get to this in the near term, if someone would like to send a PR I'd be happy to review it.

**Comment by limick** [comment]
I'll make sure it gets done.

**Comment by snoyberg** [comment]
Awesome, thanks!

**Comment by mdunnio** [comment]
@limick do you have any updates on this?

**Comment by limick** [comment]
I didn't get to it myself, but I have someone working on it now. Should be ready in a few days.

**Comment by mdunnio** [comment]
Great! Thanks for the update.

**Comment by kindaro** [comment]
@limick @mdunnio @jezen  [I uploaded a new version 0.4.2 of the package.][1] Please see if it works for you and open issues as needed — I shall do my best to fix everything timely.

[1]: https://hackage.haskell.org/package/mime-mail-ses-0.4.2

**Comment by jezen** [comment]
@kindaro New version number builds just fine for me. Thanks!
